// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { FilterPoiEndpointApiV1FilterPoiPostData, FilterPoiEndpointApiV1FilterPoiPostErrors, FilterPoiEndpointApiV1FilterPoiPostResponses, GenerateIntroductionEndpointApiV1GenerateIntroductionPostData, GenerateIntroductionEndpointApiV1GenerateIntroductionPostErrors, GenerateIntroductionEndpointApiV1GenerateIntroductionPostResponses, GeneratePoiEndpointApiV1GeneratePoiPostData, GeneratePoiEndpointApiV1GeneratePoiPostErrors, GeneratePoiEndpointApiV1GeneratePoiPostResponses, GenerateStoryEndpointApiV1GenerateStoryPostData, GenerateStoryEndpointApiV1GenerateStoryPostErrors, GenerateStoryEndpointApiV1GenerateStoryPostResponses, GenerateTourApiV1GenerateTourPostData, GenerateTourApiV1GenerateTourPostErrors, GenerateTourApiV1GenerateTourPostResponses, GenerateTtsApiV1TtsTtsPostData, GenerateTtsApiV1TtsTtsPostErrors, GenerateTtsApiV1TtsTtsPostResponses, GetPlacePhotoApiV1PlacePhotoGetData, GetPlacePhotoApiV1PlacePhotoGetErrors, GetPlacePhotoApiV1PlacePhotoGetResponses, GetThemeOptionsApiV1ThemeOptionsPostData, GetThemeOptionsApiV1ThemeOptionsPostErrors, GetThemeOptionsApiV1ThemeOptionsPostResponses, GetTourByIdApiV1TourIdIsDummyGetData, GetTourByIdApiV1TourIdIsDummyGetErrors, GetTourByIdApiV1TourIdIsDummyGetResponses, GuardrailValidationApiV1GuardrailPostData, GuardrailValidationApiV1GuardrailPostErrors, GuardrailValidationApiV1GuardrailPostResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, ReadAudioApiV1TtsAudioFilenameGetData, ReadAudioApiV1TtsAudioFilenameGetErrors, ReadAudioApiV1TtsAudioFilenameGetResponses, RootGetData, RootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Generate Tts
 *
 * Generate text-to-speech audio from the given text.
 *
 * Args:
 * request: TTSRequest containing the text to convert
 *
 * Returns:
 * TTSResponse with filename and URL
 *
 * Raises:
 * HTTPException: If text is empty or generation fails
 */
export const generateTtsApiV1TtsTtsPost = <ThrowOnError extends boolean = false>(options: Options<GenerateTtsApiV1TtsTtsPostData, ThrowOnError>) => (options.client ?? client).post<GenerateTtsApiV1TtsTtsPostResponses, GenerateTtsApiV1TtsTtsPostErrors, ThrowOnError>({
    url: '/api/v1/tts/tts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Audio
 *
 * Stream the audio file (WAV format).
 *
 * Args:
 * filename: The audio filename
 *
 * Returns:
 * FileResponse with the audio file
 *
 * Raises:
 * HTTPException: If file not found
 */
export const readAudioApiV1TtsAudioFilenameGet = <ThrowOnError extends boolean = false>(options: Options<ReadAudioApiV1TtsAudioFilenameGetData, ThrowOnError>) => (options.client ?? client).get<ReadAudioApiV1TtsAudioFilenameGetResponses, ReadAudioApiV1TtsAudioFilenameGetErrors, ThrowOnError>({ url: '/api/v1/tts/audio/{filename}', ...options });

/**
 * Get Theme Options
 *
 * Generate thematic tour options for a given location address or coordinates.
 *
 * Args:
 * request: ThemeOptionsRequest containing either address or latitude/longitude
 *
 * Returns:
 * ThemeOptionsResponse with suggested tour themes
 *
 * Raises:
 * HTTPException: If there's an error generating themes
 */
export const getThemeOptionsApiV1ThemeOptionsPost = <ThrowOnError extends boolean = false>(options: Options<GetThemeOptionsApiV1ThemeOptionsPostData, ThrowOnError>) => (options.client ?? client).post<GetThemeOptionsApiV1ThemeOptionsPostResponses, GetThemeOptionsApiV1ThemeOptionsPostErrors, ThrowOnError>({
    url: '/api/v1/theme_options',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Poi Endpoint
 *
 * Generate Points of Interest (POIs) based on user coordinates and constraints.
 *
 * This endpoint performs two steps:
 * 1. Converts latitude/longitude to address using Google Maps Geocoding API
 * 2. Generates relevant POIs using Gemini API based on the address and constraints
 *
 * Args:
 * request: GeneratePOIRequest containing coordinates and constraints
 *
 * Returns:
 * GeneratePOIResponse with user address and list of POIs
 *
 * Raises:
 * HTTPException: If there's an error in geocoding or POI generation
 */
export const generatePoiEndpointApiV1GeneratePoiPost = <ThrowOnError extends boolean = false>(options: Options<GeneratePoiEndpointApiV1GeneratePoiPostData, ThrowOnError>) => (options.client ?? client).post<GeneratePoiEndpointApiV1GeneratePoiPostResponses, GeneratePoiEndpointApiV1GeneratePoiPostErrors, ThrowOnError>({
    url: '/api/v1/generate_poi',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Filter Poi Endpoint
 *
 * Filter and verify POIs to check if they actually exist in reality.
 *
 * This endpoint uses Google Maps Places API to verify each POI.
 * Only POIs that are found and verified are included in the response.
 *
 * Args:
 * request: FilterPOIRequest containing a list of POIs to verify
 *
 * Returns:
 * FilterPOIResponse with verified POIs and statistics
 *
 * Raises:
 * HTTPException: If there's an error during verification
 */
export const filterPoiEndpointApiV1FilterPoiPost = <ThrowOnError extends boolean = false>(options: Options<FilterPoiEndpointApiV1FilterPoiPostData, ThrowOnError>) => (options.client ?? client).post<FilterPoiEndpointApiV1FilterPoiPostResponses, FilterPoiEndpointApiV1FilterPoiPostErrors, ThrowOnError>({
    url: '/api/v1/filter_poi',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Guardrail Validation
 *
 * Validate if a user's tour request is legitimate for their current location.
 *
 * This endpoint uses Gemini AI to check if the user's custom tour preferences
 * make sense given their location. For example, a "chicken rice tour" in Singapore
 * would be valid, but the same request in New York would be invalid.
 *
 * The validation result is stored in the tours table with status_code indicating
 * whether the request passed validation. The address is stored as part of the constraints.
 *
 * If the request is valid, a background process is automatically started to:
 * 1. Generate POIs based on the address and constraints
 * 2. Filter/verify the POIs using Google Maps
 * 3. Order the POIs optimally and create the tour
 *
 * You can check the tour status by calling GET /{transaction_id}/{is_dummy}
 *
 * Args:
 * request: GuardrailRequest containing constraints (including address)
 * background_tasks: FastAPI background tasks handler
 *
 * Returns:
 * GuardrailResponse with transaction_id and validation result
 *
 * Raises:
 * HTTPException: If there's an error during validation
 */
export const guardrailValidationApiV1GuardrailPost = <ThrowOnError extends boolean = false>(options: Options<GuardrailValidationApiV1GuardrailPostData, ThrowOnError>) => (options.client ?? client).post<GuardrailValidationApiV1GuardrailPostResponses, GuardrailValidationApiV1GuardrailPostErrors, ThrowOnError>({
    url: '/api/v1/guardrail',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Tour
 *
 * Generate and plan the routing of a tour.
 *
 * This endpoint takes filtered POIs and orders them optimally for a tour.
 * It updates the database with:
 * - order: Sequence in which POIs should be visited
 * - poi_title: Name of the POI
 * - address: Location address
 * - google_place_id: Google Maps Place ID
 * - google_maps_name: Official name from Google Maps
 *
 * Args:
 * request: GenerateTourRequest with transaction_id, POIs, and constraints
 *
 * Returns:
 * GenerateTourResponse with success status and POI count
 *
 * Raises:
 * HTTPException: If tour not found or error during generation
 */
export const generateTourApiV1GenerateTourPost = <ThrowOnError extends boolean = false>(options: Options<GenerateTourApiV1GenerateTourPostData, ThrowOnError>) => (options.client ?? client).post<GenerateTourApiV1GenerateTourPostResponses, GenerateTourApiV1GenerateTourPostErrors, ThrowOnError>({
    url: '/api/v1/generate_tour',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Introduction Endpoint
 *
 * Generate an introduction for the tour.
 *
 * This endpoint takes a list of POIs and generates a short introduction
 * describing the tour. It runs before story generation.
 * It updates the tour's 'introduction' field in the database.
 *
 * Args:
 * request: GenerateIntroductionRequest with transaction_id and POI list
 *
 * Returns:
 * GenerateIntroductionResponse with the generated introduction
 */
export const generateIntroductionEndpointApiV1GenerateIntroductionPost = <ThrowOnError extends boolean = false>(options: Options<GenerateIntroductionEndpointApiV1GenerateIntroductionPostData, ThrowOnError>) => (options.client ?? client).post<GenerateIntroductionEndpointApiV1GenerateIntroductionPostResponses, GenerateIntroductionEndpointApiV1GenerateIntroductionPostErrors, ThrowOnError>({
    url: '/api/v1/generate_introduction',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Generate Story Endpoint
 *
 * Generate narrative stories for POIs in a tour.
 *
 * This endpoint takes a list of POIs, generates a coherent story for each,
 * and updates the database with the stories.
 *
 * It serves as the next process after /generate_tour.
 *
 * Args:
 * request: GenerateStoryRequest with transaction_id and POI list
 *
 * Returns:
 * GenerateStoryResponse with updated POIs containing stories
 */
export const generateStoryEndpointApiV1GenerateStoryPost = <ThrowOnError extends boolean = false>(options: Options<GenerateStoryEndpointApiV1GenerateStoryPostData, ThrowOnError>) => (options.client ?? client).post<GenerateStoryEndpointApiV1GenerateStoryPostResponses, GenerateStoryEndpointApiV1GenerateStoryPostErrors, ThrowOnError>({
    url: '/api/v1/generate_story',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Tour By Id
 *
 * Get a tour by its UUID.
 *
 * This endpoint retrieves a fully typed tour object including all POIs
 * associated with the tour.
 *
 * Args:
 * tour_id: UUID of the tour to retrieve
 *
 * Returns:
 * Tour object with all details including POIs
 *
 * Raises:
 * HTTPException: If the tour is not found or there's an error retrieving it
 */
export const getTourByIdApiV1TourIdIsDummyGet = <ThrowOnError extends boolean = false>(options: Options<GetTourByIdApiV1TourIdIsDummyGetData, ThrowOnError>) => (options.client ?? client).get<GetTourByIdApiV1TourIdIsDummyGetResponses, GetTourByIdApiV1TourIdIsDummyGetErrors, ThrowOnError>({ url: '/api/v1/{tour_id}/{is_dummy}', ...options });

/**
 * Get Place Photo
 *
 * Proxy endpoint for Google Maps Places API photos.
 *
 * This endpoint fetches images from Google Maps Places API on the server side
 * to avoid CORS issues in the browser. The API key is kept secure on the server.
 *
 * Args:
 * photo_reference: The photo reference from Google Places API
 * maxwidth: Maximum width of the image in pixels (default: 800)
 *
 * Returns:
 * Image data with appropriate content-type headers
 */
export const getPlacePhotoApiV1PlacePhotoGet = <ThrowOnError extends boolean = false>(options: Options<GetPlacePhotoApiV1PlacePhotoGetData, ThrowOnError>) => (options.client ?? client).get<GetPlacePhotoApiV1PlacePhotoGetResponses, GetPlacePhotoApiV1PlacePhotoGetErrors, ThrowOnError>({ url: '/api/v1/place-photo', ...options });

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
