// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * FilterPOIRequest
 */
export type FilterPoiRequest = {
    /**
     * Transaction Id
     */
    transaction_id: string;
    /**
     * Pois
     */
    pois: Array<Poi>;
};

/**
 * FilterPOIResponse
 */
export type FilterPoiResponse = {
    /**
     * Verified Pois
     */
    verified_pois: Array<Poi>;
    /**
     * Total Input
     */
    total_input: number;
    /**
     * Total Verified
     */
    total_verified: number;
};

/**
 * GPSLocation
 */
export type GpsLocation = {
    /**
     * Lat
     *
     * Latitude coordinate
     */
    lat: number;
    /**
     * Lng
     *
     * Longitude coordinate
     */
    lng: number;
};

/**
 * GeneratePOIRequest
 */
export type GeneratePoiRequest = {
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    constraints: PoiConstraints;
};

/**
 * GeneratePOIResponse
 */
export type GeneratePoiResponse = {
    /**
     * User Address
     */
    user_address: string;
    /**
     * Pois
     */
    pois: Array<IntermediatePoi>;
};

/**
 * GenerateTourRequest
 */
export type GenerateTourRequest = {
    /**
     * Transaction Id
     */
    transaction_id: string;
};

/**
 * GenerateTourResponse
 */
export type GenerateTourResponse = {
    /**
     * Transaction Id
     */
    transaction_id: string;
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
    /**
     * Pois Count
     */
    pois_count: number;
};

/**
 * GuardrailConstraints
 */
export type GuardrailConstraints = {
    /**
     * Max Time
     */
    max_time: string;
    /**
     * Distance
     */
    distance: string;
    /**
     * Custom
     */
    custom: string;
    /**
     * Address
     */
    address: string;
};

/**
 * GuardrailRequest
 */
export type GuardrailRequest = {
    constraints: GuardrailConstraints;
};

/**
 * GuardrailResponse
 */
export type GuardrailResponse = {
    /**
     * Transaction Id
     */
    transaction_id: string;
    /**
     * Valid
     */
    valid: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IntermediatePOI
 *
 * Simplified POI model for intermediate representations before enrichment
 */
export type IntermediatePoi = {
    /**
     * Poi Title
     */
    poi_title: string;
    /**
     * Address
     */
    address: string;
};

/**
 * POI
 */
export type Poi = {
    /**
     * Order
     *
     * Order of the POI in the tour
     */
    order: number;
    /**
     * Poi Title
     *
     * Title of the POI
     */
    poi_title?: string | null;
    /**
     * Google Place Id
     *
     * Google Place ID for this POI
     */
    google_place_id: string;
    /**
     * Google Place Img Url
     *
     * Image URL from Google Places
     */
    google_place_img_url?: string | null;
    /**
     * Address
     *
     * Address of the POI
     */
    address?: string | null;
    /**
     * Google Maps Name
     *
     * Name from Google Maps
     */
    google_maps_name?: string | null;
    /**
     * Story
     *
     * Story or description for this POI
     */
    story?: string | null;
    /**
     * Pin Image Url
     *
     * URL for the pin image
     */
    pin_image_url?: string | null;
    /**
     * Story Keywords
     *
     * Keywords related to the story
     */
    story_keywords?: string | null;
    /**
     * GPS location with latitude and longitude
     */
    gps_location?: GpsLocation | null;
};

/**
 * POIConstraints
 */
export type PoiConstraints = {
    /**
     * Time
     */
    time: string;
    /**
     * Distance
     */
    distance: string;
    /**
     * User Custom Info
     */
    user_custom_info: string;
};

/**
 * TTSRequest
 */
export type TtsRequest = {
    /**
     * Text
     */
    text: string;
};

/**
 * TTSResponse
 */
export type TtsResponse = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ThemeOptionsRequest
 */
export type ThemeOptionsRequest = {
    /**
     * Address
     */
    address?: string | null;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Use Dummy Data
     */
    use_dummy_data?: boolean;
};

/**
 * ThemeOptionsResponse
 */
export type ThemeOptionsResponse = {
    /**
     * Themes
     */
    themes: {
        [key: string]: string;
    };
    /**
     * Address
     */
    address: string;
};

/**
 * Tour
 */
export type Tour = {
    /**
     * Id
     *
     * Unique identifier for the tour
     */
    id: string;
    /**
     * Theme
     *
     * Theme of the tour
     */
    theme: string;
    /**
     * Status Code
     *
     * Status code of the tour
     */
    status_code: string;
    /**
     * Max Distance Km
     *
     * Maximum distance in kilometers
     */
    max_distance_km: number;
    /**
     * Max Duration Minutes
     *
     * Maximum duration in minutes
     */
    max_duration_minutes: number;
    /**
     * Introduction
     *
     * Introduction text for the tour
     */
    introduction: string;
    /**
     * Pois
     *
     * List of Points of Interest
     */
    pois?: Array<Poi>;
    /**
     * Storyline Keywords
     *
     * Keywords for the tour storyline
     */
    storyline_keywords: string;
    /**
     * Constraints
     *
     * Constraints used for the tour
     */
    constraints?: {
        [key: string]: unknown;
    } | null;
    /**
     * Filtered Candidate Poi List
     *
     * List of candidate POIs after filtering
     */
    filtered_candidate_poi_list?: Array<Poi> | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GenerateTtsApiV1TtsTtsPostData = {
    body: TtsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tts/tts';
};

export type GenerateTtsApiV1TtsTtsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTtsApiV1TtsTtsPostError = GenerateTtsApiV1TtsTtsPostErrors[keyof GenerateTtsApiV1TtsTtsPostErrors];

export type GenerateTtsApiV1TtsTtsPostResponses = {
    /**
     * Successful Response
     */
    200: TtsResponse;
};

export type GenerateTtsApiV1TtsTtsPostResponse = GenerateTtsApiV1TtsTtsPostResponses[keyof GenerateTtsApiV1TtsTtsPostResponses];

export type ReadAudioApiV1TtsAudioFilenameGetData = {
    body?: never;
    path: {
        /**
         * Filename
         */
        filename: string;
    };
    query?: never;
    url: '/api/v1/tts/audio/{filename}';
};

export type ReadAudioApiV1TtsAudioFilenameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadAudioApiV1TtsAudioFilenameGetError = ReadAudioApiV1TtsAudioFilenameGetErrors[keyof ReadAudioApiV1TtsAudioFilenameGetErrors];

export type ReadAudioApiV1TtsAudioFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetThemeOptionsApiV1ThemeOptionsPostData = {
    body: ThemeOptionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/theme_options';
};

export type GetThemeOptionsApiV1ThemeOptionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetThemeOptionsApiV1ThemeOptionsPostError = GetThemeOptionsApiV1ThemeOptionsPostErrors[keyof GetThemeOptionsApiV1ThemeOptionsPostErrors];

export type GetThemeOptionsApiV1ThemeOptionsPostResponses = {
    /**
     * Successful Response
     */
    200: ThemeOptionsResponse;
};

export type GetThemeOptionsApiV1ThemeOptionsPostResponse = GetThemeOptionsApiV1ThemeOptionsPostResponses[keyof GetThemeOptionsApiV1ThemeOptionsPostResponses];

export type GeneratePoiEndpointApiV1GeneratePoiPostData = {
    body: GeneratePoiRequest;
    path?: never;
    query?: never;
    url: '/api/v1/generate_poi';
};

export type GeneratePoiEndpointApiV1GeneratePoiPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GeneratePoiEndpointApiV1GeneratePoiPostError = GeneratePoiEndpointApiV1GeneratePoiPostErrors[keyof GeneratePoiEndpointApiV1GeneratePoiPostErrors];

export type GeneratePoiEndpointApiV1GeneratePoiPostResponses = {
    /**
     * Successful Response
     */
    200: GeneratePoiResponse;
};

export type GeneratePoiEndpointApiV1GeneratePoiPostResponse = GeneratePoiEndpointApiV1GeneratePoiPostResponses[keyof GeneratePoiEndpointApiV1GeneratePoiPostResponses];

export type FilterPoiEndpointApiV1FilterPoiPostData = {
    body: FilterPoiRequest;
    path?: never;
    query?: never;
    url: '/api/v1/filter_poi';
};

export type FilterPoiEndpointApiV1FilterPoiPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FilterPoiEndpointApiV1FilterPoiPostError = FilterPoiEndpointApiV1FilterPoiPostErrors[keyof FilterPoiEndpointApiV1FilterPoiPostErrors];

export type FilterPoiEndpointApiV1FilterPoiPostResponses = {
    /**
     * Successful Response
     */
    200: FilterPoiResponse;
};

export type FilterPoiEndpointApiV1FilterPoiPostResponse = FilterPoiEndpointApiV1FilterPoiPostResponses[keyof FilterPoiEndpointApiV1FilterPoiPostResponses];

export type GuardrailValidationApiV1GuardrailPostData = {
    body: GuardrailRequest;
    path?: never;
    query?: never;
    url: '/api/v1/guardrail';
};

export type GuardrailValidationApiV1GuardrailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GuardrailValidationApiV1GuardrailPostError = GuardrailValidationApiV1GuardrailPostErrors[keyof GuardrailValidationApiV1GuardrailPostErrors];

export type GuardrailValidationApiV1GuardrailPostResponses = {
    /**
     * Successful Response
     */
    200: GuardrailResponse;
};

export type GuardrailValidationApiV1GuardrailPostResponse = GuardrailValidationApiV1GuardrailPostResponses[keyof GuardrailValidationApiV1GuardrailPostResponses];

export type GenerateTourApiV1GenerateTourPostData = {
    body: GenerateTourRequest;
    path?: never;
    query?: never;
    url: '/api/v1/generate_tour';
};

export type GenerateTourApiV1GenerateTourPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateTourApiV1GenerateTourPostError = GenerateTourApiV1GenerateTourPostErrors[keyof GenerateTourApiV1GenerateTourPostErrors];

export type GenerateTourApiV1GenerateTourPostResponses = {
    /**
     * Successful Response
     */
    200: GenerateTourResponse;
};

export type GenerateTourApiV1GenerateTourPostResponse = GenerateTourApiV1GenerateTourPostResponses[keyof GenerateTourApiV1GenerateTourPostResponses];

export type GetTourByIdApiV1TourIdIsDummyGetData = {
    body?: never;
    path: {
        /**
         * Tour Id
         */
        tour_id: string;
        /**
         * Is Dummy
         */
        is_dummy: boolean;
    };
    query?: never;
    url: '/api/v1/{tour_id}/{is_dummy}';
};

export type GetTourByIdApiV1TourIdIsDummyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTourByIdApiV1TourIdIsDummyGetError = GetTourByIdApiV1TourIdIsDummyGetErrors[keyof GetTourByIdApiV1TourIdIsDummyGetErrors];

export type GetTourByIdApiV1TourIdIsDummyGetResponses = {
    /**
     * Successful Response
     */
    200: Tour;
};

export type GetTourByIdApiV1TourIdIsDummyGetResponse = GetTourByIdApiV1TourIdIsDummyGetResponses[keyof GetTourByIdApiV1TourIdIsDummyGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
